---
title: "p8105_hw6_nl2835"
author: "Nancy Le"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
library(rnoaa)
set.seed(1)
```

## Problem 2

```{r Central Park weather data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

```{r bootstrapping}
boot_sample = function(weather_df) {
  sample_n(weather_df, size = nrow(weather_df), replace = TRUE)
}
```



```{r bootstrap regression}
bootstrap_reg <- function(df) {
  regression <- lm(tmax ~tmin + prcp, data = df)
  r2 <- summary(regression)$r.squared
  beta_1 <- coef(regression)["tmin"]
  beta_2 <- coef(regression)["prcp"]
  beta_inter <- beta_1 * beta_2 
  
  if (beta_inter <= 0) {
    logbetainter <- NA } else {
      logbetainter <- log(beta_inter)
    }
  
  tibble(r2 = r2, logbetainter = log(beta_inter))
}

boot_straps <- 
  tibble(strap_number = 1:5000) |> 
  mutate(
    strap_sample = map(strap_number, ~boot_sample(weather_df)), 
    bootstrap_results = map_dfr(strap_sample, ~bootstrap_reg(.x |> as_tibble()))
  )
```

```{r}
boot_straps
```


```{r plot estimates of R2}
ggplot(boot_straps, aes(x = bootstrap_results$r2)) +
  geom_histogram(binwidth = 0.01, fill = "blue", color = "black") + 
  labs(title = "R-squared Estimates Distribution", 
       x = "R^2",
       y = "Frequency")
```

The distribution of r-squared estimates centers around R2 = 0.92 and is a symmetric distribution. 

```{r plot estimates of log(beta interecepts)}
ggplot(boot_straps, aes(x = bootstrap_results$logbetainter)) +
  geom_histogram(binwidth = 0.05, fill = "lightgreen", color = "black") + 
  labs(title = "Log Interaction Estimates", 
       x = "log(beta1*beta2)",
       y = "Frequency")
```

The distribution of log(b0 * b1) estimates is skewed left, with a median around -6. 

```{r compute r2 CI}
r_squared_quantiles <- quantile(boot_straps$bootstrap_results$r2, probs = c(0.025, 0.975), na.rm = TRUE)
```

```{r compute log CI}
logbetainter_quantiles <- quantile(boot_straps$bootstrap_results$logbetainter, probs = c(0.025, 0.975), na.rm = TRUE)
```

```{r print values}
r_squared_quantiles
logbetainter_quantiles
```



